services:
  - type: web
    name: examgen-ghori
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: A4F_API_KEY
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
